# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# site settings
repository: lxynox/cv
baseurl: "/cv"                              # the subpath of your site, e.g. /blog
url: "https://lxynox.github.io"             # the base hostname & protocol for your site

# app specific
title: cv
email: lxynox@gmail.com
description: >
    Shitty personal cv built with hybrid front-end little tricks

# defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "lxynox"

# Build settings
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
theme: "minima"
